version: "3.8"

services:
  land-grants-api:
    image: land-grants-api:development
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - PORT_DEBUG=9229
      - MONGO_URI=mongodb://root:example@mongo:27017
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - cdpuploader

  farming-grants-agreements-api:
    image: farming-grants-agreements-api:development
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - PORT_DEBUG=9230
      - MONGO_URI=mongodb://root:example@mongo:27017
    ports:
      - "3001:3001"
      - "9230:9230"
    networks:
      - cdpuploader

  land-grants-ui:
    image: land-grants-ui:development
    depends_on:
      - land-grants-api
      - farming-grants-agreements-api
    environment:
      - PORT=3002
      - PORT_DEBUG=9231
      - API_BASE_URL=http://land-grants-api:3000
    ports:
      - "3002:3002"
      - "9231:9231"
    networks:
      - cdpuploader

  farming-grants-ui:
    image: farming-grants-ui:development
    depends_on:
      - farming-grants-agreements-api
      - land-grants-api
    environment:
      - PORT=3004
      - PORT_DEBUG=9233
      - API_BASE_URL=http://farming-grants-agreements-api:3001
    ports:
      - "3004:3004"
      - "9233:9233"
    networks:
      - cdpuploader

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    networks:
      - cdpuploader

volumes:
  redisinsight:
  mongo-data:

networks:
  cdpuploader:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
